function LogInfo = LoadLog(LogFilePath)
% Use: LogInfo = LoadLog(LogFilePath)
%
% LogInfo - a structure contains all the parameter values as well as their
% field names in a log file generated by VsgCtrl
% LogFilePath - full path to log file
%
% This function simply read .log file generated by VsgCtrl during data
% recording, and try to store values with fieldnames into a structure for
% convinient (hopefully future use)
%
LogFilePath = [LogFilePath(1:end-4) '.log'];
if exist(LogFilePath,'file')==2 % check file avaliability
    fprintf('\n\n\nLoadLog Working on File:\n%s\n',LogFilePath);
    LogFileId = fopen(LogFilePath,'r');
    currline = 'dummy';
    numfield = 0;
    while ischar(currline)
        currline = fgetl(LogFileId);
        position = strfind(currline,'=');
        if ~isempty(position)
            tmp = textscan(currline,'%s','Delimiter','=');
            tmp = tmp{1};
            numfield = numfield + 1;
            if isempty(tmp)
                error('Empty Left Hand Side')
            else
                fieldnames{numfield} = tmp{1}(1:end-1);
                if numel(tmp) == 1
                    tmp{2} = 'N/A';
                end
            end
            fieldvalue{numfield} = tmp{2};
            
        else
            % currently do nothing
        end
    end
% % %     NumFieldnames = numel(fieldnames);
% % %     for i = 1:NumFieldnames
% % %         % replace white spaces in fieldnames with '_'
% % %         poz = fieldnames{i} == ' ';
% % %         fieldnames{i}(poz) = '_';
% % %         % replace reserved charactors with '_'
% % %         poz = fieldnames{i} == '+';
% % %         fieldnames{i}(poz) = '_';
% % %         poz = fieldnames{i} == '-';
% % %         fieldnames{i}(poz) = '_';
% % %         poz = fieldnames{i} == '*';
% % %         fieldnames{i}(poz) = '_';
% % %         poz = fieldnames{i} == '/';
% % %         fieldnames{i}(poz) = '_';
% % %         poz = fieldnames{i} == '.';
% % %         fieldnames{i}(poz) = '_';
% % %         % eliminate '(' and ')'
% % %         poz = fieldnames{i} == '(';
% % %         fieldnames{i}(poz) = '';
% % %         poz = fieldnames{i} == ')';
% % %         fieldnames{i}(poz) = '';
% % %         % if field name start with a number, add '_' in front of the name
% % %         if ~isempty(str2num(fieldnames{i}(1)))
% % %             fieldnames{i} = ['PRE_' fieldnames{i}];
% % %         end
% % %     end
% % %     % check for field name duplication
% % %     for i = 1:NumFieldnames
% % %         NumDup = 0;
% % %         for j = (i+1):NumFieldnames
% % %             if strcmp(fieldnames{i},fieldnames{j})
% % %                 NumDup = NumDup + 1;
% % %                 fieldnames{j} = [fieldnames{j} '_' num2str(NumDup)];
% % %             end
% % %         end
% % %     end
% % %     LogInfo = cell2struct(fieldvalue,fieldnames,2);
    LogInfo.fieldnames = fieldnames;
    LogInfo.fieldvalue = fieldvalue;
    % save LogInfo to mat
    [savepath, savedir] = GetSavePath(LogFilePath,'LogInfo.mat');
    if exist(savedir,'dir') == 7
    else
        mkdir(savedir)
    end
    save(savepath,'LogInfo')
    if ispc
        cmd = ['copy ' LogFilePath ' ' savedir];
        dos(cmd);
    else
        cmd = ['cp ' LogFilePath ' ' savedir];
        unix(cmd);
    end
    fclose(LogFileId);
else
    error('.log file not exist!')
end