function [MbmNumtrials, MbmInfo, MBMFieldNames,sMbmInfo] = LoadMbm(mbmfilepath)
% Use: [MbmNumtrials, MbmInfo, MBMFieldNames,sMbmInfo] = LoadMbm(mbmfilepath,matversion)
%
% This function will try its best to guess the information stored in mbm
% file that generated by VsgCtrl, and store it in a MbmInfo matrix.
%
% revised by Wang Feng, 2012/11/12

disp('LoadMbm working on file:')
disp(mbmfilepath)

% if not exist, create a folder after the name of the mbm file to store the
% result
MatDir = mbmfilepath(1:end-4);
if exist(MatDir,'dir')~=7
    mkdir(MatDir);
end
% in case mbmfilepath not ended with .mbm
mbmfilepath = [mbmfilepath(1:end-3) 'mbm'];
% open the file in read only mode
mbmid = fopen(mbmfilepath,'r');
% the first line should always be "@VSG_MBM log:"
CurrLine = fgetl(mbmid);
if strcmp(CurrLine,'@VSG_MBM log:')
    % Ok to proceed
else
    error('MBM first line is incorrect, wrong file or file corruption!')
end
% jump to section "[COLUMN_TITLE_DEFINITION]"
while ~strcmp(CurrLine,'[COLUMN_TITLE_DEFINITION]')
    CurrLine = fgetl(mbmid);
end
Nfields = 0;
while 1 %~strcmp(CurrLine,'[DATA_BEGIN]')
    CurrLine = fgetl(mbmid);
    if ~strcmp(CurrLine,'[DATA_BEGIN]')
        tmp = textscan(CurrLine,'%s','Delimiter','=');
        Nfields = Nfields + 1; % count the number of fields in the mbmfile
        MBMFieldNames(Nfields) = tmp{1}(1); % Get MBM field names
    else
        break;
    end
end
MbmNumtrials=0;
while ischar(CurrLine);
    CurrLine = fgetl(mbmid);
    MbmNumtrials=MbmNumtrials+1;
end
MbmNumtrials = MbmNumtrials - 1;
MbmInfo = zeros(Nfields,MbmNumtrials);
frewind(mbmid);
while ~strcmp(CurrLine,'[DATA_BEGIN]')
    CurrLine = fgetl(mbmid);
end
for i = 1:MbmNumtrials
    CurrLine = fgetl(mbmid);
    temp = textscan(CurrLine,'%f',Nfields);
    MbmInfo(1:numel(temp{1}),i) = temp{1};
end
fclose(mbmid);
% sort matrix into a structure array for easy access
c_MbmInfo = mat2cell(MbmInfo,ones(Nfields,1),MbmNumtrials);
sMbmInfo = cell2struct(c_MbmInfo,MBMFieldNames,1);
FileName = [mbmfilepath(1:end-4) '/' 'mbminfo.mat'];
% if file exist, overwrite
if exist(FileName,'file') == 2
    delete(FileName)
end
save(FileName,'MbmInfo','MBMFieldNames','MbmNumtrials','sMbmInfo');
if ispc
    cmd = ['copy ' mbmfilepath ' ' MatDir];
    dos(cmd);
else
    cmd = ['cp ' mbmfilepath ' ' MatDir];
    unix(cmd);
end
return