function figure1 = create_age_h_figure
%CREATEFIGURE(X1, Y1, S1, C1, XDATA1, YDATA1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c
%  XDATA1:  line xdata
%  YDATA1:  line ydata

%  Auto-generated by MATLAB on 02-Apr-2015 11:48:43

% use neuroelf
n = neuroelf;

% data
X1 = [37; 44; 41; 43; 43; 42; 46; 48; 46; 57; 58; 58; 65; 67; 69; 71; 73; 76; 78; 85; 87];
Y1 = [22; 22; 27; 15; 23; 34; 19; 36; 62; 41; 40; 53; 46; 49;100; 37; 61; 39; 30; 82; 26];
N1 = {'JC'; 'DM'; 'NT'; 'VPV'; 'DS'; 'FC'; 'SW'; 'CH'; 'KO'; 'NB'; 'GD'; ...
      'EW'; 'JM'; 'RS'; 'TEH'; 'NG'; 'DH'; 'DK'; 'HT'; 'WM'; 'LM'};

% add 1000 low-visible lines
axes1 = axes;
l = zeros(2000, 1);
for lc = 2000:-1:1
    r1 = ceil(21 * rand(21, 1));
    X1r = X1(r1, :);
    Y1r = Y1(r1, :);
    xx = [ones(21, 1), X1r];
    b = n.fitrobustbisquare(xx, Y1r);
    if b(2) > 0
        l(lc) = line([32; 92], b(1) + [32; 92] .* b(2));
    else
        l(lc) = [];
    end
end
set(l, 'LineWidth', 0.25, 'Color', [0.9, 0.9, 0.9]);

% create scatter
[axes1, rs] = n.robscatter(X1, Y1, struct('ax', axes1, 'hold', true, ...
    'cbands', true, 'cbandz', 3, ...
    'cweight', 0.5, 'dcolor', zeros(21, 3), 'ocolor', [1, 1, 1]));
figure1 = get(axes1, 'Parent');
set(figure1, 'Position', [300, 300, 1152, 864]);
axch = get(axes1, 'Children');
set(axch(1:3), 'Color', [0, 0, 0], 'LineWidth', 1.5);
set(axch(4), 'MarkerEdgeColor', [0.5, 0.5, 0.5], 'MarkerFaceColor', 'flat', ...
    'SizeData', 72, 'CData', ...
    rs{1}.w(:, [1,1,1]) .* zeros(21, 3) + (1 - rs{1}.w(:, [1,1,1])) .* ones(21, 3));
set(figure1, 'Color', [1, 1, 1]);
set(axes1, 'FontSize', 14);
xlim(axes1,[30 92]);
ylim(axes1,[0 120]);

% Create text
text('Parent', axes1, 'FontSize', 12, 'String', 'r=0.4404, p<0.05', 'Position',[84, 48, 0]);

% label dots
XD = X1 - mean(X1);
XD = log(3 + log(1 + abs(XD))) .* sign(XD) - 0.5;
YD = Y1 - mean(Y1);
YD = log(3 + log(1 + abs(YD))) .* sign(YD);
for dc = 1:numel(N1)
    text('Parent', axes1, 'FontSize', 7, 'String', N1{dc}, ...
        'Position', [X1(dc) + XD(dc), Y1(dc) + YD(dc), 0]);
end

% Create xlabel
xlabel('age (y)');

% Create ylabel
ylabel('h index');

% Create title
title('h index as a function of age', 'FontSize', 16);

% save figure
print(figure1, '-r600', '-dpng', 'age-h-corr2.png');
im = imread('age-h-corr2.png');
imr = n.image_resize(im, 0.5);
imwrite(imr, 'age-h-corr2r.png');
